### ISSUE TITLE
Add top header

### ISSUE THREAD

**Issue by Eric-Arellano** [ParkingReformNetwork/reform-map#142]
This is what it currently looks like on https://parkingreform.org/mandates-map/

<img width="1336" alt="Captura de pantalla 2023-06-17 a la(s) 8 35 41 a m" src="https://github.com/ParkingReformNetwork/mandates-map/assets/14852634/18c717ab-23b5-4172-8ab1-182db55e8667">

Along with this clickable info button:

<img width="157" alt="Captura de pantalla 2023-06-17 a la(s) 8 36 19 a m" src="https://github.com/ParkingReformNetwork/mandates-map/assets/14852634/089c9a89-2177-4fb6-8834-0c299e3fa0e2">

We can have a similar header to our PLM, except that we won't have the city toggle and need to add the share buttons. I think the information button should move from the map to the top header bar. And we could get rid of that lightbulb button and move it to the information button.

<img width="1332" alt="Captura de pantalla 2023-06-17 a la(s) 8 36 59 a m" src="https://github.com/ParkingReformNetwork/mandates-map/assets/14852634/46585ee6-4682-4c92-8ad2-7b9d75cd12c0">

You'll need to copy some of the JavaScript code, like how we set up FontAwesome icons and our code for the information button to be clickable. You'll also need to copy the styling. It's okay for us to use PLM's styling—no need for it to be identical to the mandates map.

Check if any of the tests from PLM would be relevant to copy over.

**Comment by tunglinn** [comment]
Steps:
1. Create banner div with title
2. Move map zoom controls down
3. Install fontAwesome (dependencies and js)
4. Add info and fullscreen icon with functionality
5. Install bootstrap (dependencies and js)
6. Add share icon with dropdown using bootstrap

**Comment by Eric-Arellano** [comment]
This has been done thanks to @tunglinn :) I opened https://github.com/ParkingReformNetwork/reform-map/issues/188 and https://github.com/ParkingReformNetwork/reform-map/issues/189 to track the more specific follow ups since those are both advanced
