### ISSUE TITLE
Empty .csv files

### ISSUE THREAD

**Issue by tunglinn** [ParkingReformNetwork/reform-map#168]
Not sure why the live site is still running.

tidied_map_data.csv and trimmed_map_data.csv are empty after the last data update.

### To Implement ###
A test to check if running `npm run update-map-data` writes empty .csv files.

**Comment by twjordan** [comment]
Fortunately the live site runs on shinyapp and is updated manually. 

But this is preventing new updates. so this is the highest priority bug.

**Comment by twjordan** [comment]
Ok, so somethingn happened about two weeks ago. Between pull request 161 and 166. Somewhere in there something changed so the update map data script failed and blanked out the csv files.

**Comment by tunglinn** [comment]
I'll work on this. And also write a test to catch this, if it ever happens again.

**Comment by twjordan** [comment]
Any update on this? Do we know what caused it? could it be a csv library bug?

**Comment by tunglinn** [comment]
Still working on it. Looked through the code, but still have some questions.
- After someone submits a parking mandates report form, how does the data get "into" the map? 
- What I see is that our update scripts might be fetching from a Google Sheet (or something similar in csv)?

**Comment by tunglinn** [comment]
When testing a prior version (before PR161), running updateMapData.js would output empty .csv files.

It seems like the report .csv is not being fetched. So when the script runs a left join, the output is going to be nothing.

**Comment by tunglinn** [comment]
@twjordan Seems like there's something wrong with the header. This is the most recent download for the city report.

![image](https://github.com/ParkingReformNetwork/mandates-map/assets/86996158/f6848e80-9002-4ae0-be80-81ad6e21e753)

**Comment by twjordan** [comment]
Ok, so what is happening here is that the Column header in the Report table got changed to Salt Lake, which broke the export from google tables. I changed it back but I am not sure if that is enough to fix the problem, we need to re-check in the csv files from 161 and have the script run against them.

**Comment by Eric-Arellano** [comment]
Great detective work @tunglinn! Tony updated the Google Table. This is now working after the revert from https://github.com/ParkingReformNetwork/mandates-map/pull/174 and then re-running the scripts in https://github.com/ParkingReformNetwork/mandates-map/pull/175.

@tunglinn, it would be great to add a unit test that both CSV files have >1900 lines. We only ever change the CSVs via a pull request, and those PRs will run CI. So, the unit test would have prevented this from happening. Great instinct to want to add a test :) That's called "regression testing" -- when you fix something, it's good to add an automated test to make sure we don't repeat the mistake.

The test would use JavaScript's filesystem API (using async/await) to read in the files. Then it would check that the # of lines is > 1900.
