### ISSUE TITLE
Add filter mechanism

### ISSUE THREAD

**Issue by Eric-Arellano** [ParkingReformNetwork/reform-map#186]
<img width="277" alt="Captura de pantalla 2023-08-17 a la(s) 8 47 14 p m" src="https://github.com/ParkingReformNetwork/reform-map/assets/14852634/c8b19495-a6aa-4414-92d5-0a1269932218">

**Comment by tunglinn** [comment]
We can use a larger package like [Semantic UI](https://semantic-ui.com/).
Or find individual features that we want, like this [multiple select React component](https://www.npmjs.com/package/multiselect-react-dropdown).

**Comment by tunglinn** [comment]
- [ ] Filter popup
- [ ] Dropdown options
- [ ] Population slider
