### ISSUE TITLE
Needs UI feedback: Filter popup takes up too much vertical space

### ISSUE THREAD

**Issue by Eric-Arellano** [ParkingReformNetwork/reform-map#265]

**Comment by tunglinn** [comment]
Does this mean we do not want the scrolling in the filter popup? What is the goal of having a shorter popup?

**Comment by Eric-Arellano** [comment]
I think we need UI feedback to confirm what we should do. The original idea of this ticket was to return to something similar to Shiny, where we hide the options behind an expandable list

<img width="297" alt="Captura de pantalla 2023-10-17 a la(s) 3 53 29 p m" src="https://github.com/ParkingReformNetwork/reform-map/assets/14852634/5e2ebbe1-f817-4cbc-9921-110c7fa79a62">

<img width="280" alt="Captura de pantalla 2023-10-17 a la(s) 3 54 16 p m" src="https://github.com/ParkingReformNetwork/reform-map/assets/14852634/b946066e-c218-4bd4-b164-893c3f4a4bc3">

I'm no longer convinced that's a good idea, though. I think the "Select All" and "Deselect All" isn't very important since we don't have very many options to begin with. It's easy to close out of the filter popup. And it's a simpler UX to have fewer buttons to click with the current implementation.
