### ISSUE TITLE
Dots don't show up when you scroll to the right or left

### ISSUE THREAD

**Issue by twjordan** [ParkingReformNetwork/reform-map#368]
When you scroll past the initial projection of the globe the dots are not there. They only show on one tile.

**Comment by Eric-Arellano** [comment]
@tunglinn sounds good to me https://github.com/ParkingReformNetwork/reform-map/pull/371#issuecomment-2140623981

**Comment by Eric-Arellano** [comment]
I limited zoom out, so this is now fixed.
