### ISSUE TITLE
Default view should at least highlight/display the number of US cites with no parking mandates.

### ISSUE THREAD

**Issue by twjordan** [ParkingReformNetwork/reform-map#369]
It should be very obvious on load that we are looking at cities with no parking mandates, all uses, citywide and - if possible, the number of cities in the US should be called out.

**Comment by tunglinn** [comment]
Default view: All US cities with no parking requirements for all uses.
(no search bar, no filter, no legend) Add a "Explore more" button to go to Expanded view.

Expanded view: search bar, filter popup, legend.

**Comment by Eric-Arellano** [comment]
The default view now shows all places with mandates, and the counter gives context to what you're seeing. We want the first view to be as impressive as possible that lots of places have reforms, so it should not be US-centric on the very first load.

However, we definitely should allow getting only US entries. That is tracked by https://github.com/ParkingReformNetwork/reform-map/issues/373
