### ISSUE TITLE
Make sure all cities show up if all filters are checked

### ISSUE THREAD

**Issue by tunglinn** [ParkingReformNetwork/reform-map#374]
For example, this is with all the filters checked.
![image](https://github.com/ParkingReformNetwork/reform-map/assets/86996158/a84d4071-8d54-4b20-9b9c-f54743173026)

To-do:
- [ ] Figure out why the last few cities aren't showing
- [ ] Create a test to check

**Comment by Eric-Arellano** [comment]
Duplicate of https://github.com/ParkingReformNetwork/reform-map/issues/260
